### ISSUE TITLE
Matlab bug

### ISSUE THREAD

**Issue by Cschweiger90** [akarimp/oceanlyz#1]
Hi,

I've tried to run the example in Matlab, but following error occured:

...
Copyright (C) 2012-2021 Arash Karimpour
Error using oceanlyz/oceanlyzmodule
Too many input arguments.

Error in oceanlyz/runoceanlyz (line 1093)
            [obj.module]=obj.oceanlyzmodule(obj);

Is there any solution for this?

Best regards!

**Comment by akarimp** [comment]
Hi,

The provided MATLAB example is run on GNU Octave 6.2 and it did not cause any error.
If you can provide more detail it can help to find the source of the error.

Thanks,
