### ISSUE TITLE
OCEANLYZ - Too Many Input Arguments

### ISSUE THREAD

**Issue by jaymerrill** [akarimp/oceanlyz#2]
Hi Dr. Karimpour, 

My name is Jay Merrill and I am a master's student here at Louisiana State University. We recently installed several RBR pressure sensors in Barataria Bay and I am in the process of analyzing the raw pressure data. I came across your OCEANLYZ MatLab code and felt it would be the perfect method to begin assessing the data. 

I did, however, run into the same issue as the previous request that was closed in May. After trying a variety of inputs (.csv, .mat, .txt, all as one column vectors), I continue to receive, "Error using oceanlyz/oceanlyzemodule. Too many input arguments - Error in oceanlyz/runoceanlyz (line 1093) [obj.module]=obj.oceanlyzmodule(obj);

I understand your previous comment was regarding Octave, but as a student I am running all this analysis in MatLab R2020B. Do you have any advice on how to resolve this issue? 

Thank you for your time and for providing what I hope will be a great method to analyze wave data. 

Best, 

Jay Merrill

**Comment by akarimp** [comment]
Thanks Jay, I fixed the bug.
