### ISSUE TITLE
a typo in oceanlyz.m?

### ISSUE THREAD

**Issue by lzhu5** [akarimp/oceanlyz#4]
Hi Arash, in oceanlyz.m, Line 150 - 153, SeparateSeaSwell='yes' means "Separates wind sea and swell waves", right? It is stated oppositely in the code.

**Comment by akarimp** [comment]
Hi,

Yes, that was a typo. The correct document is:

SeparateSeaSwell='no';
    Define if to separate wind sea and swell waves or not
        | SeparateSeaSwell='no': Does not separate wind sea and swell waves
        | SeparateSeaSwell='yes': Separates wind sea and swell waves
